name: Durable
main: com.modcrafting.under50.Durable
version: 0.1
authors: [Deathmarine]
commands:
  durability:
    description: 
    permission: durable.command
    usage: /<command> <get|repair>
permissions:
  durable.*:
    default: op
    description: Allows the Administration to Full Control
    children:
      durable.command: true
  durable.command:
    description: Allows players to use the /durability command.