name: AnvilDisable
main: com.modcrafting.under50.AnvilDisable
version: 0.1
website: http://modcrafting.com
author: Deathmarine
description: >
            Plugin for Bukkit.
permissions:
  anvildisable.*:
    description: Allows the Administration to Full Control
    children:
      anvildisable.override: true
  anvildisable.override:
    default: op
    description: Allows player to use an anvil